# -*- coding: utf-8 -*-
"""FineTuning-DEMO1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gfkSz-mhFIVJrvQnFsZRkYw6OEQO4fWV
"""

!pip install transformers datasets peft accelerate bitsandbytes

from datasets import Dataset

data = [
    {"text": "User: Where is my order?\nAssistant: I'm sorry for the delay. Please share your order ID so I can check the status."},
    {"text": "User: I want refund\nAssistant: I understand your concern. Let me guide you through the refund process."},
    {"text": "User: Product is damaged\nAssistant: I apologize for the inconvenience. Please share an image so we can assist quickly."},
]

dataset = Dataset.from_list(data)

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16
)

tokenizer = AutoTokenizer.from_pretrained(model_name)

from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)

def tokenize(example):
    tokens = tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

    tokens["labels"] = tokens["input_ids"].copy()
    return tokens

dataset = dataset.map(tokenize)

from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=2,
    num_train_epochs=3,
    logging_steps=5,
    save_strategy="no"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset
)

trainer.train()

input_text = "User: I want refund\nAssistant:"
inputs = tokenizer(input_text, return_tensors="pt").to("cuda")

output = model.generate(**inputs, max_new_tokens=50)

print(tokenizer.decode(output[0], skip_special_tokens=True))

model.save_pretrained("lora_adapter")
tokenizer.save_pretrained("lora_adapter")

from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import torch

base_model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

# Load base model
model = AutoModelForCausalLM.from_pretrained(
    base_model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

# Load LoRA adapter
model = PeftModel.from_pretrained(model, "lora_adapter")

tokenizer = AutoTokenizer.from_pretrained("lora_adapter")

input_text = "User: I want refund\nAssistant:"
inputs = tokenizer(input_text, return_tensors="pt").to("cuda")

output = model.generate(**inputs, max_new_tokens=50)

print(tokenizer.decode(output[0], skip_special_tokens=True))

import os
os.listdir("lora_adapter")

from google.colab import files
files.download("lora_adapter/adapter_model.safetensors")

!zip -r lora_adapter.zip lora_adapter

files.download("lora_adapter.zip")



"""# Step 1: Installing Libraries

**In the first step, we installed all the required libraries such as Hugging Face Transformers, PEFT, and other supporting packages. These libraries help us load pre-trained models, handle datasets, and perform fine-tuning efficiently. Without these, we cannot proceed with model training or customization.**

# Step 2: Creating Dataset

**In this step, we created our dataset directly inside Google Colab using JSON format. The dataset contains instruction-response pairs related to customer support. This is important because the model learns from this data, and creating it inside Colab makes the project simple and easy to manage without uploading external files.**

# Step 3: Loading Dataset

**Here, we loaded the dataset using a dataset library so that it can be used for training. The raw JSON data is converted into a structured format that the model can understand. This step is necessary because the training process requires properly formatted data.**

# Step 4: Loading Pre-trained Model

**In this step, we loaded a pre-trained language model and tokenizer. We also used a 4-bit quantization method to reduce memory usage. This allows us to run large models efficiently in limited environments like Colab. The pre-trained model already has general knowledge, which we will now customize.**

# Step 5: Applying LoRA

**Here, we applied LoRA to the model. Instead of training the entire model, LoRA adds small adapter layers and trains only those. This makes the process faster and requires less memory, making it suitable for systems with limited resources.**

# Step 6: Formatting Dataset

**In this step, we converted the dataset into a proper prompt format by combining instruction and response into a single text. This helps the model understand how to respond correctly based on a given instruction. Proper formatting is important for effective learning.**

# Step 7: Tokenization

**Here, we converted the text data into tokens (numerical format) using the tokenizer. Since models cannot understand text directly, tokenization is required. We also added labels so that the model knows what output it should generate during training.**

# Step 8: Training the Model

**In this step, we trained the model using the prepared dataset. The model learns patterns from the data, and we can observe the training progress through decreasing loss values. This is the main step where fine-tuning actually happens.**

# Step 9: Saving the Model

**After training, we saved the fine-tuned model and tokenizer. This allows us to reuse the model later without retraining. Saving is important for deployment and testing purposes.**

# Step 10: Testing the Model

**Finally, we tested the model by giving sample inputs and checking the output. We compared the responses before and after fine-tuning to confirm that the model has improved and is now giving more accurate and domain-specific answers.**

# Difference Between Google Colab and Local System

**Fine-tuning can be done either using Google Colab or on a local system (your laptop/PC). The main difference is where the computation happens. In Colab, all the processing is done on Google’s cloud servers, while in a local system, everything runs on your own hardware. Colab provides free access to GPUs, which makes it easier to run large models without needing a powerful computer. In contrast, a local system depends completely on your device’s specifications such as RAM and GPU.**

# Pros and Cons of Local System

**A local system gives full control over the environment and does not have time limits like Colab. You can run long training processes without interruption, and your data remains private. However, it requires a powerful system with a good GPU, high RAM, and proper setup of libraries and drivers. Without a GPU, training becomes very slow and difficult.**

# Which is Easier?

**For beginners, Google Colab is much easier because it does not require installation or hardware setup. You can directly start coding and training models. A local system is more suitable for advanced users who have proper hardware and want more control.**
"""